# give super user permissions
sudo: required

# set language
language: generic

# tell travis what we need
services:
  - docker

before_install:
  - docker build -t alexrosenkranz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexrosenkranz/docker-react npm run test